# site default theme ["auto", "light", "dark"]
defaultTheme = "auto"
# public git repo url only then enableGitInfo is true
gitRepo = ""
# LoveIt NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
# ["sha256", "sha384", "sha512", "md5"]
fingerprint = ""
# LoveIt NEW | 0.2.0 date format
dateFormat = "2006-01-02"

# 页面头部导航栏配置
[header]
# 桌面端导航栏模式 ("fixed", "normal", "auto")
desktopMode = "fixed"
mobileMode = "auto"
[header.title]
    logo = ""
    name = "Home"
    post = ""
    typeit = false

[home]
# LoveIt NEW | 0.2.0 amount of RSS pages
rss = 10
# Home page profile
[home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/avatar.png"
    title = ""
    subtitle = "learning and writing"
[[plugins.js]]
link = "js/tab.js"
